included:
  - Sources
  - Tests

excluded:
  - .build

reporter: "xcode"

opt_in_rules:
  - explicit_init
  - empty_count

disabled_rules:
  - todo
  - cyclomatic_complexity
  - function_body_length

line_length:
  warning: 160
  error: 240
